### PR TITLE
Adding typeahead for contains strings

### PR DESCRIPTION
**Pull request by AbhiAgarwal**
For our project we needed way to do a typeahead on strings. This is helpful for us (in our project) in a couple reasons:

1. Load 1-5 fields as you're typing and then get more specific. 
2. For properties, we wanted to add a way to understand their internal representation. It's kind of hard to understand what underlies in a property - some of our properties are just choices (but can't be represented as choices).

Using the MassAutoComplete javascript package.

I've added a basic typeahead with a solution implemented on the front-end. Let me know of your thoughts! Happy to improve/develop this idea further.

### CODE REVIEW

**Comment by grantjenks** [comment]
Can you provide more details? I don't know what a typeahead is nor MassAutoComplete.

Also it looks like you're missing tests.

**Comment by bufke** [comment]
Yeah I'm confused as well. It looks like it adds typeahead (or auto-complete where you start typing and choices pop up) but under what circumstances would this happen? What can I do in the demo project to demonstrate the feature?

**Comment by AbhiAgarwal** [comment]
Thanks for the feedback. Sorry for not being precise enough in what this feature would do for the project. I'm introducing this typeahead/autocomplete feature. Basically - this is how it would work:

1. You're adding a filter. That filter is for the model Bar, and the field is `char_field`. 
2. You begin typing in some values. The idea is that you'll see something below your text box that completes the value you're currently typing. So if you're typing "hel", and the model has the following rows: "hello", "hell", "jeans". Then the typeahead would show "hello", "hell". 

I took a screenshot of how this would work (as currently implemented through this PR)



This is important for our project for a couple reasons:

1. We have a lot of fields across a lot of models and a autocomplete really helps non-technical/model-savy people understand the data and make better reports.
2. We can make @property values smarter on the front-end. Some of our properties are actually choices, but in our model we determine the current choice by a method. We can get the unique values and make them a choices field instead.
3. We can make other values smarter on the front-end as well. For example, a date-time picker can have better ranges if it knows the limitations behind the data itself. 

MassAutoComplete is the javascript package I chose to use to implement this feature on the front-end. This was something I've used in the past, and provided a really easy and customizable way to add this feature to report builder. It also works well with AngularJS.

I've also added a backend test to see if it returns the correct values.

@bufke To do a demo - you can just pull this codebase, add some values, and then add a filter. Then just begin typing in to the filter. I think it starts after you have two-three words in the textbox. This demo works on my end!

**Comment by bufke** [comment]
Are there any performance considerations with this? It seems to be limited to 10 results right? I think we may want a settings variable to enable this. If it doesn't appear to have performance issues with larger databases we could consider defaulting to enabled.

Are reasons 2 and 3 implemented in this pull? Where are the choices defined in 2? I would assume 3 would need to be an additional change right?

**Comment by bufke** [comment]
Closing due to age - but please feel free to resubmit.

**Pull request closed without merging**
