### PR TITLE
Adaptation for Django 1.10

### PR DESCRIPTION
**Pull request by brawaga**
Without this patch I have no opportunity to build reports through many-to-many and reverse FKs.

### CODE REVIEW

**Comment by bufke** [comment]
Would you have time to contribute a unit test that passes in 1.9, fails in 1.10, but passes with this change? Unit tests are the best defense against regressions and keeping the code base maintainable with minimal time.

**Comment by brawaga** [comment]
@bufke, I understand, but I am short in time now.

**Comment by bufke** [comment]
If I find any time I'll improve the docs on how unit tests should be written. The tests are just in one file [here](https://github.com/burke-software/django-report-builder/blob/master/report_builder/tests.py). You can run the demo app manually or by using docker - see the including docker-compose.yml file. Then just test with `./manage.py test` as you would for any django project.

If someone can add unit tests here I'll merge it.

**Comment by bufke** [comment]
The utils issue was fixed. If there are other issues please open a new pull request with test. Changes that can break various django versions without a test proving which versions work will not be accepted.

**Pull request closed without merging**
