### PR TITLE
Adding properties to the list of the display fields

### PR DESCRIPTION
**Pull request by Resousse**
Hi, according to my request #259 , here the implementation to enable properties support in the display fields

Let me know if this change is ok
Thanks

### CODE REVIEW

**Comment by Resousse** [comment]
I don't understand the coverage error, could you explain?

**Comment by kmmbvnr** [comment]
@Resousse you've added the code, that don't covered by the tests

https://coveralls.io/builds/9937870/source?filename=report_builder%2Fapi%2Fviews.py#L231

**Comment by Resousse** [comment]
Cool, now waiting for the merge! :)

**Comment by Resousse** [comment]
I had another bug, occuring when there is a is null filter on items, this was interpreting True checkbox like string and didn't work

**Comment by Resousse** [comment]
I had a bug, when I set two exclude filters, only the last exclude apply and not the first one... My last commit fix that

**Comment by Resousse** [comment]
Finally found that a specific code is needed to allow property via django report builder

```
class model1(models.Model):
   props and fields...
   @property
    def property1(self):
        return "ok"
   class ReportBuilder:
        extra = ['property1', ]
```
And voila, the property is displayed!
An example would be appreciated, in addition to the existing doc : https://django-report-builder.readthedocs.io/en/latest/quickstart/

**Pull request closed without merging**
