### PR TITLE
invoked function to prevent 'function object not iterable error'

### PR DESCRIPTION
**Pull request by willseward**

### CODE REVIEW

**Comment by bufke** [comment]
Can you explain this one a bit? Under what circumstances does it fail? Is it unit testable?

**Comment by willseward** [comment]
Sure! The ```pk__in``` key expects a list, but now is passing in a function. I'm not sure why this breaks in 1.9, and I can't find it in the change logs. All I did was invoke the function before passing it to the field.

**Comment by bufke** [comment]
Strange. I wonder if this means the get_allowed_models will now run on startup instead of at each request. Shouldn't make any difference unless someone was really messing with that function.

**Comment by willseward** [comment]
That's a valid concern. I suppose it would run on startup. I'm looking into finding the breaking change in django. 

Can you reproduce this error on 1.9?

**Comment by willseward** [comment]
I just extracted the entire choices dict to a method that it is evaluated by https://github.com/django/django/blob/b61eab18f71f3afb36b3e8cb208a145046b3d8f6/django/db/models/fields/related.py#L360

**Comment by willseward** [comment]
Geez, I just failed at python 101. The changes should be good now.

**Comment by willseward** [comment]
For some reason I can't get the tests to run properly on my machine, so I didn't know if that was going to pass.

**Pull request merged**
