### PR TITLE
importing get_column_letter from openpyxl.utils

### PR DESCRIPTION
**Pull request by predatell**
importing get_column_letter from openpyxl.cell does not work for latest versions

and using active property instead deprecated get_active_sheet

indents for flake8 check in admin.py

### CODE REVIEW

**Comment by bufke** [comment]
Is this still compatible with openpyxl 2.2.1? If not this would have to go into a 4.0 release.

Don't change the version numbers in setup.py - I can do that when pushing to pypi

**Comment by predatell** [comment]
This is still compatible with openpyxl 2.2.1

**Comment by predatell** [comment]
If you can change the versions when pushing to pypi please do it. But when I detect this issue I saw version 3.4.3 at pypi and 3.4.2 in repo in setup.py. I think it was not correct. And how can I show you changes in install_requires without changes in setup.py?

**Comment by bufke** [comment]
Oh - I only meant the report builder version, not the install_requires.

**Pull request merged**
