### PR TITLE
Add max and min annoation filters

### PR DESCRIPTION
**Pull request by grantjenks**
Similar to group-by queries, annotation-filters allow you to display only the Max or Min of a set of rows.

Suppose we have two models, Person and Child. Each has `first_name`, `last_name` fields and Child has a foreign key to Person as `parent`. Child also has `age` and `color` fields. Already we can use the group-by mechanism to display each Person's count of children or the age of each person's oldest child.

Unfortunately, getting the related items of an aggregate is difficult in Django and SQL. Suppose in the example above that we want to know the name and age of each person's oldest child. With annotation-filters this can be done.

Annotation-filters are applied iteratively after normal queryset filtering. They work, as the name indicates, by applying Django's annotate and filter queryset methods. As they are self-referential, they do not accept a text input from the front-end.

Annotation-filters are difficult to describe conceptually so I'll use an example. To display the name and age of each person's oldest child, we begin by constructing a report based on Child. We add display fields for the parent name, child name, and child age. Then for filter fields, we add the `parent__children__age` field. This lengthy path indicates that children are to be grouped by their parent and with the type `Max`, only the maximum age of each group should be included.

We could extend this further by adding the filter field `parent__children__color` with type `Equals` `Red` to get a list of the oldest children of each person whose favorite color is red.

This change extends the tests based on Person and Child with coverage for the above described scenarios.

### CODE REVIEW

**Comment by grantjenks** [comment]
For reference, on the difficulty of getting related items in aggregates: http://blog.roseman.org.uk/2010/08/14/getting-related-item-aggregate/

And an alternate solution using annotate and filter (used here): http://stackoverflow.com/questions/2839145/django-aggregation-query-on-related-one-to-many-objects

@bufke or @saulshanabrook Can you code review before I merge? I'd also like to make a release with this new functionality.

**Comment by grantjenks** [comment]
@bufke I plan to merge this tomorrow to resolve a client issue. Feedback welcome before then.

**Comment by bufke** [comment]
I've thought a lot about aggregation in this project. I agree it is quite difficult. Uses cases that sound easy in English can get complex in ORM and SQL. Trying to explain to a user who isn't a database expert how aggregation works is also difficult. 

We should document this behavior. It is not apparent just looking at the UI. Unfortunately our [How to docs](https://github.com/burke-software/django-report-builder/blob/master/docs/howto.md) are badly out of date. I'll see if I can get around to updating them.

On the unit test itself - could you add a summary of what you wrote above? On general direction - does it make sense to add docstrings to unit test as a specification for developers to review and then an end user "how to guide" on the page I linked. We don't have to do all this just to merge this one pull.

**Comment by grantjenks** [comment]
@bufke I agree about the test docstrings. I've added the notes from this pull request to those for future reference.

Personally, I think the how-to docs do more to advertise the project. I found it very intuitive as a developer. For my clients, a few walk-throughs and examples do the trick. It would be nice to give them a guide but with how much things change, I doubt it would last.

**Pull request merged**
