### PR TITLE
Correct the model used for meta and property lookups on related models

### PR DESCRIPTION
**Pull request by tolomea**
the get GetFieldsMixin looks up the field on the model to find the actual class, however previously it didn't pass it up to the calling view, so that view did lookups based on the parent model, not the related model

### CODE REVIEW

**Comment by bufke** [comment]
Could you add a test that shows how it failed before and works now?

**Comment by bufke** [comment]
I'm confused here. In your example you start with the bar model and reference foo fields (foo is related). Foo has char_field and char_field2. This was working fine. But with your change it stops working and your test checks to make sure char_field2 doesn't show up - which it should.

What is the intent of this change? Perhaps describe in terms of the demo app and what report you'd expect and what you get instead.

I did notice this change removed some invalid fields on foos. "i_want_char_field" and "i_need_char_field" Those are from the Bar model but incorrectly show up as options when I click Foos. Is that what you are trying to fix? We just need to fix that without causing regressions.

**Comment by tolomea** [comment]
My understand and expectation is that char_field2 shouldn't show up because
it's not listed in Foo.ReportBuilder.fields.
More broadly that Foo.ReportBuilder should constrain what you see on Foo
regardless of whether you are accessing Foo directly or via a field on Bar.
Prior to this change if you access Foo via a field on Bar the code
constrains Foo based on Bar.ReportBuilder which seems to me like a straight
up bug.

**Comment by bufke** [comment]
Ah I see what you mean now. Makes sense.

**Comment by bufke** [comment]
Thanks!

**Pull request merged**
