### PR TITLE
Add tests for group-by and sorting and totals and field formatting

### PR DESCRIPTION
**Pull request by grantjenks**
Add tests for the following:

* Group-by foreign key id
* Group-by foreign key first_name and last_name (multiple fields)
* Make test_get_relation_fields_from_model compatible with Django 1.7 & 1.8
* Test all aggregates: Max, Min, Avg, Count, Sum
* Test sorting with nulls and reverse
* Test choices field display and missing choices
* Test formatter works and is aligned correctly with totals.

### CODE REVIEW

**Comment by grantjenks** [comment]
This depends on https://github.com/burke-software/django-report-utils/pull/14

This resolves Issue #20 (which depends on django-report-utils being updated) and adds tests to maintain correctness.

**Comment by grantjenks** [comment]
This also resolves Issue #158

**Comment by grantjenks** [comment]
Travis-CI failed due to the dependency on https://github.com/burke-software/django-report-utils/pull/14

**Comment by bufke** [comment]
I'm getting unit test errors even with your report utils change. Can you confirm this? I also fixed a python 3 errors in report utils - please test against python 3.

```
ERROR: test_choices_and_sort_null (report_builder.tests.ReportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/report_builder/tests.py", line 584, in test_choices_and_sort_null
    response = self.client.get(generate_url)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 160, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 86, in get
    return self.generic('GET', path, **r)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/compat.py", line 222, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 448, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/report_builder/api/views.py", line 162, in get
    return self.post(request, report_id=report_id)
  File "/code/report_builder/api/views.py", line 180, in post
    preview=True,)
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 382, in report_to_list
    row[position] = text_type(choice_list[row[position]])
KeyError: 'Y'

======================================================================
ERROR: test_groupby_id (report_builder.tests.ReportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/report_builder/tests.py", line 414, in test_groupby_id
    response = self.client.get(generate_url)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 160, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 86, in get
    return self.generic('GET', path, **r)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/compat.py", line 222, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 448, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/report_builder/api/views.py", line 162, in get
    return self.post(request, report_id=report_id)
  File "/code/report_builder/api/views.py", line 180, in post
    preview=True,)
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 334, in report_to_list
    reverse=sort_field[1]
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 333, in <lambda>
    key=lambda x: self.sort_helper(x, sort_value),
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 441, in sort_helper
    result = x[sort_key]
IndexError: tuple index out of range

======================================================================
ERROR: test_groupby_name (report_builder.tests.ReportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/report_builder/tests.py", line 468, in test_groupby_name
    response = self.client.get(generate_url)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 160, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 86, in get
    return self.generic('GET', path, **r)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/compat.py", line 222, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 451, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 448, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/report_builder/api/views.py", line 162, in get
    return self.post(request, report_id=report_id)
  File "/code/report_builder/api/views.py", line 180, in post
    preview=True,)
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 334, in report_to_list
    reverse=sort_field[1]
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 333, in <lambda>
    key=lambda x: self.sort_helper(x, sort_value),
  File "/usr/local/lib/python3.4/site-packages/report_utils/mixins.py", line 441, in sort_helper
    result = x[sort_key]
IndexError: tuple index out of range

======================================================================
FAIL: test_formatter (report_builder.tests.ReportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/report_builder/tests.py", line 630, in test_formatter
    self.assertContains(response, data)
  File "/usr/local/lib/python3.4/site-packages/django/test/testcases.py", line 358, in assertContains
    msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find '"data":[["Charles","King","None years old"],["Helen","King","7 years old"],["James","Doe","8 years old"],["Karen","Smith","4 years old"],["Lisa","King","3 years old"],["Mark","King","2 years old"],["Robert","Doe","3 years old"],["Susan","Smith","1 years old"],["Will","Doe","5 years old"],["TOTALS","",""],["","","33 years old"]]' in response

----------------------------------------------------------------------
Ran 24 tests in 3.585s

FAILED (failures=1, errors=3)
```

**Comment by grantjenks** [comment]
Sorry! I merged wrong and accepted remote when I meant to accept local. I've fixed the bad merge in django-report-utils this morning and tested this again. Everything is passing for me now.

**Comment by grantjenks** [comment]
If you version-bump django-report-utils again, release it, and update django-report-build to depend on that then Travis CI should pass. I would do this myself but I can't publish django-report-utils to PyPI.

**Comment by bufke** [comment]
Do you have a username on pypi? I could give you access.

**Comment by grantjenks** [comment]
Username: Grant.Jenks

But you're sure you want to do that? I don't know what kind of automated deployments you might have that'll automatically pick up the latest versions. Personally, my projects are small enough for me to manage dependencies manually.

How many others are using this?

**Comment by bufke** [comment]
I think it would be healthy for any project to have more than one maintainer. Anyone else using this should be aware of the risks of not pinning version numbers and I have released regressions in the past as I'm only human. 

For some organization - can you get my sign off on new versions of django-report-builder? Just open a pull request that changes the version number. Go ahead and try to get travis to pass by updating report utils, I'll check against projects, and then we can release report builder build. Use sdist and bdist_wheel please.

If you aren't comfortable making releases you can wait till I find the time to do so as well.

**Comment by grantjenks** [comment]
I'm comfortable with it. I think the pull-request on version numbers is a good idea. That'll work fine. Go ahead and add me.

**Comment by bufke** [comment]
@grantjenks you should have access to everything, let me know if otherwise. Sorry I actually gave you access 6 days ago but didn't tell you.

**Comment by bufke** [comment]
Had some time and just merged it myself. Looks good. Made a pypi release.

**Comment by grantjenks** [comment]
Thanks

**Pull request merged**
